### ISSUE TITLE
Configuration warning at 'custom.safeguards': should be object

### ISSUE THREAD

**Issue by Kamahl19** [serverless/safeguards-plugin#14]
I am getting `Configuration warning at 'custom.safeguards': should be object` warning with this simple config
```
custom:
  safeguards:
    - safeguard: no-wild-iam-role-statements
```

Policies run fine, no idea why there is a warning

**Comment by Kamahl19** [comment]
This is actually caused by the enterprise-plugin https://github.com/serverless/enterprise-plugin/blob/689e9b2c22e80e8708e603628ad669b2c59c2b35/lib/plugin.js#L104

**Comment by medikoo** [comment]
@Kamahl19 thanks for reporting. I'm going to close it in favor of https://github.com/serverless/enterprise-plugin/issues/521
