### ISSUE TITLE
Policies and deployment as separate serverless.yaml?

### ISSUE THREAD

**Issue by deitch** [serverless/safeguards-plugin#4]
I am looking at using policies to enforce corporate security and compliance requirements. The challenge I am running up against is that the behaviours we want to control (deploying lambdas, setting IAM, etc.) and the enforcement rules are in the same location, i.e. `serverless.yaml`.

Is there a way to run policies to apply to a _different_ yaml file? The workflow I am thinking of is something like this:

1. app dev creates their serverless.yaml as usual, runs locally or against their own AWS dev environment
1. PR opened, approved, merged
1. Our policies are in a separate repo under InfoSec/Compliance dept control
1. CD applies the compliance-controlled policies against the appdev-controlled serverless.yaml

Sort of (pseudo-code): 

```
sls safeguard --policy git/infosec/policies/serverless.yaml --input ./serverless.yaml
```

If it passes, we deploy with `sls deploy`; if not, we reject.

Can that be done?

**Comment by medikoo** [comment]
@deitch I understand that use case is to validate service against externally defined safeguards (not bundled with a serverless file)

Technically closest to that, would be to use variables where you resolve safeguards from external file, which is resolved on bases of CLI options, something as:

```
custom:
  safeguards: ${file(${opt:policy}):safeguards}
```

One culprit is that will crash if developer doesn't locally use `--policy` and doesn't have corresponding file, but that probably can be worked around with:

```
custom:
  safeguards: ${file(${opt:policy, ""}):safeguards, ""}
```

_(still I haven't tested that_).

See https://www.serverless.com/framework/docs/providers/aws/guide/variables/ for full documentation on variables

**Comment by deitch** [comment]
Hi @medikoo thanks for the quick response.

Yeah, what I really am after is "validate this file against the policy defined in this different file". Until I can do that, it is hard to make this work with corporate policies. I have devs who really like the framework, and want to use it to define their own setups. They use it for their own dev environments and local stack, and are quite pleased.

Now they want to use it as part of the deployment (lower environments, eventually production) toolchain. For me to give it to them, I have to be able to validate their configs against my policies.

Shall we leave it open as a request?

**Comment by medikoo** [comment]
@deitch have you tried to achieve it with options I listed?

**Comment by deitch** [comment]
@medikoo yes they would work, but, again, in a compliance or regulated environment, those policies (or some of them) _must_ be out of the hands of the person writing the serverless.yaml . 

Let's turn it around. I am an app-dev. I open my PR, and do something that violates the policy. It is late, I am pressured, so I just remove that include. It deploys.

In a well-controlled enterprise, that should not be able to happen. I should not be _able_ to remove the include. It just isn't up to me.

**Comment by deitch** [comment]
Separately, is there any way to run _just_ the validation? Something like `serverless safeguard -c serverless.yaml` and tell me if it passes or not?

**Comment by medikoo** [comment]
> In a well-controlled enterprise, that should not be able to happen. I should not be able to remove the include. It just isn't up to me.

Ok, so question is about ensuring given policies unconditionally on given service

> Separately, is there any way to run just the validation? Something like serverless safeguard -c serverless.yaml and tell me if it passes or not?

Currently there isn't.

I believe your proposal is totally valid, I imagine it as:

```
sls safeguards validate --config path/to/policies-config.yml
```

and if  `--config` is not provided it should validate against configuration as is in service

PR that implements that is definitely welcome!

**Comment by deitch** [comment]
> Ok, so question is about ensuring given policies unconditionally on given service

Yeah, exactly. An opportunity to include policies from a different file would be great.

> PR that implements that is definitely welcome!

Will try to find some time to do it. Stay tuned.

**Comment by deitch** [comment]
I find myself trying to understand the plugin design by reverse-engineering how various plugins are written, as well as the core code itself. Is there a good starting guide?

**Comment by medikoo** [comment]
@deitch this should be a good start: https://www.serverless.com/blog/writing-serverless-plugins/

Over there you should find information on how to configure commands. Rest probably is best if learned via reverse engineering. We also have [Anatomy](https://github.com/serverless/serverless/blob/master/docs/anatomy.md) document that outlines flow of a CLI process, might be helpful as well.

If you approach some specific difficulty with hard to find answer, just ask here

**Comment by deitch** [comment]
Actually, I think it was simple than I thought. I hadn't realized that plugins - even optional ones - extend the CLI, so updating just this plugin will, when included, extend the CLI options. I had thought I needed to extend the core github.com/serverless/serverless, which was getting messy.

Getting closer here.

**Comment by deitch** [comment]
OK, getting there. I got stuck on the attempt to scan the `.serverless` dir. The original implementation did it only pre-deploy, so it reasonably expected to find artifacts in there post-package. Here, we just want to validate. Do I need to package first? How do I trigger that?

**Comment by deitch** [comment]
Oh interesting. Does it validate the input `serverless.yaml` with all of its includes? Or only the output (cloudformation for AWS, etc.)?

**Comment by deitch** [comment]
Separate question. Now that I already am digging into this and going to open a PR for validate on its own (once I have an understanding of the packaging requirement above), would you consider a PR for the core issue here? Where I could do:

```
sls safeguards validate --policy=path/to/some/policy
```

wherein it would use both the policy in the config serverless.yaml and the added policy path?

**Comment by medikoo** [comment]
> Do I need to package first? How do I trigger that?

You may follow same steps as deploy does (it also invokes packaging): 

https://github.com/serverless/serverless/blob/5f85543d8e47a9afaec6811a57e1235e82949550/lib/plugins/deploy/deploy.js#L121-L123

> Does it validate the input serverless.yaml with all of its includes? Or only the output (cloudformation for AWS, etc.)?

It depends on a rule, as I see most validate result template (as that's the final source of truth), but some others as [allowed-regions](https://github.com/serverless/safeguards-plugin/blob/master/safeguards/policies/allowed-regions.js) validate resolved configuration

> wherein it would use both the policy in the config serverless.yaml and the added policy path?

I believe this can be done in context of a plugin (no need for changes to core). It's more a question of design, do we want the safeguards as configured in service to be always validated and  treat `--policy` as an extra validation. Or do we want to override the validation with `--policy`.
Doing first feels right to me

**Comment by deitch** [comment]
> do we want the safeguards as configured in service to be always validated and treat --policy as an extra validation. Or do we want to override the validation with --policy.
Doing first feels right to me

Agreed. Just because we have an outside policy doesn't mean the internal policy is no longer valid. It should be additive.

> I believe this can be done in context of a plugin (no need for changes to core)

I think so too. I will get a separate PR in for it once this one is in.

**Comment by deitch** [comment]
> You may follow same steps as deploy does (it also invokes packaging):

I will try it thanks.

**Comment by deitch** [comment]
See #5 

Once we have that in a good state and in, I will open a separate PR for the additional policy option.

**Comment by deitch** [comment]
@medikoo I have a few questions around the next stage (and then we can close this one too).

* is there a way to add multiple CLI flags, e.g. `sls safeguards validate --policy-file path/to/one.yaml --policy-file path/to/two.yaml ...`. Granted you can do that with a single file and includes, but if there is a way that the flags can support it, no reason why not
* I am trying to figure out where to add that. I can add the option as a subset of `sls safeguards validate`, but then it would apply only when running an explicit `sls safeguards validate`, and not when running as part of the `before:deploy:deploy` hook. I can extend the function called with that hook, but how do I add the option to the safeguards plugin so that `sls deploy --policy-file=path/to/file.yaml` would work in addition to `sls safeguards validate --policy-file=path/to/file/yaml`?

Thanks

**Comment by medikoo** [comment]
> @medikoo I have a few questions around the next stage

Sure, no problem

> is there a way to add multiple CLI flags

I believe in that case you'll automatically have all values provided as array on `options['policy-file']`

>  but how do I add the option to the safeguards plugin so that `sls deploy --policy-file=path/to/file.yaml` would work

For each command that supports it, the option should be set individually, and for commands that are configured in core you can extend options, for that you need to get to the plugin object as e.g. it's done here:

https://github.com/serverless/enterprise-plugin/blob/cc1853ad0ef3c1a4eb41aed349ced42546fbe31a/lib/plugin.js#L310-L317

I know it's obscure, but unfortunately it's the only way now.

**Comment by KerberosMorphy** [comment]
I know a CLI command would be more than welcome, but I think a workaround could work with @medikoo suggestion:

```yaml
custom:
  safeguards: ${file(${opt:policy, ""}):safeguards, ""}
```

You would need to check if `serverless.yml` did have `safeguards: ${file(${opt:policy, ""}):safeguards, ""}` set before deploying. Like that, if the developer remove it you should be able to detect it an block the deployment.

However, I am interested in and command line solution like `sls safeguards validate --policy=path/to/some/policy`, my main use would be too enforce or allow specific plugins, if you're interesting there's a custom policy I made [allowed-plugins.js](https://gist.github.com/KerberosMorphy/d0620271c22723e48cca6966e7b6c64c).

**Comment by deitch** [comment]
@KerberosMorphy see #5 which was merged in a few days ago. You now can run `sls safeguards validate` as a standalone. It doesn't yet have the option for a separate policy file, but that will be there soon.
