### ISSUE TITLE
v1.0.2 tag for latest changes

### ISSUE THREAD

**Issue by timglass00** [serverless/safeguards-plugin#8]
Having recently come across this plugin I followed the installation instructions on the README.md, only to encounter various serverless errors about `sls safeguards validate` not being a valid command.

I eventually realised that this is because the README.md displayed by github is from the master branch, and the way `sls safeguards` was invoked historically in v1.0.1 is different. Manually installing the plugin based on commit [d953141](https://github.com/serverless/safeguards-plugin/commit/d953141ab23f0e625bcffc83b02fa7da8abdbf08) confirms this is the underlying issue.

Could I request that a new v1.0.2 release is made to include @deitch's recent changes for #4 so that other developers don't struggle to use this plugin in the way I have?

Thanks!

**Comment by medikoo** [comment]
@timglass00 Published with v1.1.0

**Comment by timglass00** [comment]
Thanks @medikoo - much appreciated
